version: '3.1'
services:
  stats-server:
    build: ewm-stats-service/stats-service
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"

#  stats-db:
#    image: postgres:14-alpine

  ewm-service:
    build: ewm-main-service
    image: main_server_image
    container_name: main_server_container
    ports:
      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
